name: build-app-for-testing-session
on:
  issue_comment:
    types: [created]
    
env:
  app_name: SparkDemo
  pr_comment_name: "/buildDemo"
  xcode_path: "/Applications/Xcode_15.4.app"
  xcodebuild_sdk: -sdk iphonesimulator
  xcodebuild_derivedData: ".derivedData/"
  xcodebuild_destination: -destination 'platform=iOS Simulator,name=iPhone 15 pro,OS=17.5'

jobs:
  long-job:
    name: Check if Pull Request Comment contains '/buildDemo'
    runs-on: macos-14
    if: ${{ github.event.issue.pull_request && github.event.comment.body == '/buildDemo' }}
    steps:
    - name: Copy sourcery from common packages repository
      run: |
        git clone https://github.com/adevinta/spark-ios
        cd spark-ios
    - name: Select Xcode
      run: sudo xcode-select -s ${{ env.xcode_path }}
    - name: Checkout Action
      uses: actions/checkout@v4
    - name: Get current folder
      run: |
        echo "Current folder"
        pwd
        ls
        echo '-------'
    - name: Run xcodegen
      uses: xavierLowmiller/xcodegen-action@1.2.2
      with:
        spec: spark-ios/project.yml
        version: '2.41.0'
    - name: Build
      run: |
        xcodebuild -scheme ${{ env.spm_name }} -derivedDataPath ${{ env.xcodebuild_derivedData }} ${{ env.xcodebuild_sdk }} ${{ env.xcodebuild_destination }} -resultBundlePath ${{ env.app_name }}.xcresult build
    - name: Upload xcresult file
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: ${{ env.app_name }}-${{ github.run_number }}.xcresult
        path: ${{ env.app_name }}.xcresult
        retention-days: 15
    - name: Upload build file
      uses: actions/upload-artifact@v4
      if: ${{ success() }}
      with:
        name: SparkDemo.app
        path: |
          ${{ env.xcodebuild_derivedData }}/Build/Products/Debug-iphonesimulator/SparkDemo.app
        retention-days: 15